# Automatic property, do not touch!
config-version: 4

port: 6418

# mineserv.top
mineserv-top-key: ""

# mctop.im
mctop-im-secret: ""

# topcraft.club
topcraft-club-key: ""

# Enables the route /test?username=[username]
# Warning: Should NEVER EVER be true
# in production, for test purposes only.
enable-test-route: false
